service: mutual-steam-games-backend
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  region: eu-west-2
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: ANY