version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0.1-node
    steps:
      - checkout
      - run:
          name: Set up NPM
          command: npm ci
      - run:
          name: Run unit tests
          command: npm run itest
      - run:
          name: Run integration tests
          command: npm run itest
      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
          paths:
            - node_modules

  e2e-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: run e2e tests
          command: npm run e2etest

  deploy-stage:
    docker:
      - image: cimg/openjdk:15.0.1-node
        environment:
          SLS_DEBUG: '*'
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
      - run:
          name: deploying to stage
          command: |
            echo ${AWS_ACCESS_KEY_ID}
            echo ${AWS_SECRET_ACCESS_KEY}
            npm run deploy -- -s stage

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test
      - e2e-test:
          requires:
            - build-and-test
      - deploy-stage:
          requires:
            - e2e-test
          filters:
            branches:
              only: main