version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0.1-node
    steps:
      - checkout
      - run:
          name: Set up NPM
          command: sudo npm ci --unsafe-perm
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
          paths:
            - node_modules

  aws-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}

  deploy-stage:
    docker:
      - image: cimg/openjdk:15.0.1-node
        environment:
          SLS_DEBUG: '*'
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
      - run:
          name: deploying to stage
          command: |
            npm run deploy -- -s stage

workflows:
  build_and_deploy:
    jobs:
      - build-and-test
      - aws-setup
      - deploy-stage:
          requires:
            - build-and-test
            - aws-setup
          filters:
            branches:
              only: main