version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.2


jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0.1-node
    steps:
      - checkout
      - run:
          name: Set up NPM
          command: npm ci
      - run:
          name: Run unit tests
          command: npm run itest
      - run:
          name: Run integration tests
          command: npm run itest
      - save_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
          paths:
            - node_modules

  aws-setup:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Set up NPM
          command: npm ci

  deploy-stage:
    docker:
      - image: cimg/openjdk:15.0.1-node
        environment:
          SLS_DEBUG: '*'
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package-lock.json" }}-v1
      - run:
          name: deploying to stage
          command: |
            npm run deploy -- -s stage

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test
      - aws-setup:
          requires:
            - build-and-test
      - deploy-stage:
          requires:
            - aws-setup
          filters:
            branches:
              only: main